{% set name = "7zip" %}
{% set version = "24.08" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://downloads.sourceforge.net/project/sevenzip/7-Zip/{{ version }}/7z{{ version.replace('.', '') }}-src.7z
  sha256: fc459c2314a032231c157fd3257906c070ceed11efd6ffa621c2dfebbbc31281

build:
  number: 0
  skip: true  # [not win]

requirements:
  build:
    - {{ compiler('cxx') }}
  run_constrained:
    - 7za <0.0.0a

test:
  commands:
    - 7z.exe
    - 7za.exe
    - 7zr.exe

about:
  home: https://www.7-zip.org/
  license: LGPL-2.1-or-later AND LGPL-2.1-or-later WITH unRAR-restriction
  license_file:
    - LICENSE.txt
    - UNRAR_LICENSE.txt
  summary: 7-Zip is a file archiver with a high compression ratio.
  dev_url: https://sourceforge.net/p/sevenzip/

extra:
  recipe-maintainers:
    - wolfv
