schema_version: 1

context:
  name: 7zip
  version: 24.08

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://downloads.sourceforge.net/project/sevenzip/7-Zip/${{ version }}/7z${{ version | replace('.', '') }}-src.tar.xz
  sha256: 4df7a62e5ce503892f500b1f96f0a954931c5266900c439102040957b25a90c6

build:
  number: 2
  skip: not win

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
  run_constraints:
    - 7za <0.0.0a

tests:
  - script:
      - 7z.exe
      - 7za.exe
      - 7zr.exe

about:
  license: LGPL-2.1-or-later AND LicenseRef-LGPL-2.1-or-later-with-unRAR-restriction
  license_file:
    - LICENSE.txt
    - UNRAR_LICENSE.txt
  summary: 7-Zip is a file archiver with a high compression ratio.
  homepage: https://www.7-zip.org/
  repository: https://sourceforge.net/p/sevenzip/

extra:
  recipe-maintainers:
    - wolfv
