schema_version: 1

context:
  name: 7zip
  version: 24.08

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/ip7z/7zip/archive/${{ version }}.tar.gz
  sha256: a37ab4537d8d2f63b5d6e6aa7300dd9fa728823fa90a7e99bc063c31d6f5dac5

build:
  number: 2
  skip: not win

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
  run_constraints:
    - 7za <0.0.0a

tests:
  - script:
      - 7z.exe
      - 7za.exe
      - 7zr.exe
      - 7zz.exe

about:
  license: LGPL-2.1-or-later AND LicenseRef-LGPL-2.1-or-later-with-unRAR-restriction
  license_file:
    - LICENSE.txt
    - UNRAR_LICENSE.txt
  summary: 7-Zip is a file archiver with a high compression ratio.
  homepage: https://www.7-zip.org/
  repository: https://github.com/ip7z/7zip

extra:
  recipe-maintainers:
    - wolfv
