schema_version: 1

context:
  name: 7zip
  version: "26.00"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/ip7z/7zip/archive/${{ version }}.tar.gz
  sha256: 07eafed75d661282d402dc2a3edf17e1dbb36fb813f4fbf5a2bad4f6b722aed5

build:
  number: 0

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - if: not win
      then:
        - make
    - if: osx
      then:
        - uutils-coreutils
  run_constraints:
    - 7za ==999999999

tests:
  - script:
      - 7z
      - 7za
      - 7zr
      - 7zz

about:
  license: LGPL-2.1-or-later AND LicenseRef-LGPL-2.1-or-later-with-unRAR-restriction
  license_file:
    - LICENSE.txt
    - UNRAR_LICENSE.txt
  summary: 7-Zip is a file archiver with a high compression ratio.
  homepage: https://www.7-zip.org/
  repository: https://github.com/ip7z/7zip

extra:
  recipe-maintainers:
    - XhstormR
    - wolfv
